url: http://home.ustc.edu.cn
baseurl: /~ibug

theme: minima
title: "iBug 的科大主页"
description: "使用 Jekyll 构建"

exclude:
  - '.*'
  - '*.yml'
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - /script
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
